api: 1
name: hello
lang: c++

plugins:
  - LED

sources:
  - main.cpp

config:
  BLINK_INTERVAL:
    desc: The interval of blinking (in msec)
    type: int
    default: 1000
  LED_PIN:
    desc: The LED to be blinked
    type: int
    default: 13
